// Australian Tax Brackets for 2022-2023
export const TAX_BRACKETS = [
  { min: 0, max: 18200, rate: 0, base: 0 },
  { min: 18201, max: 45000, rate: 0.19, base: 0 },
  { min: 45001, max: 120000, rate: 0.325, base: 5092 },
  { min: 120001, max: 180000, rate: 0.37, base: 29467 },
  { min: 180001, max: Infinity, rate: 0.45, base: 51667 }
];

// Medicare Levy
export const MEDICARE_LEVY_RATE = 0.02;
export const MEDICARE_LEVY_THRESHOLD = 23365;
export const MEDICARE_LEVY_FAMILY_THRESHOLD = 39402;

// HECS/HELP Repayment Thresholds and Rates
export const HECS_HELP_THRESHOLDS = [
  { min: 0, max: 48360, rate: 0 },
  { min: 48361, max: 55836, rate: 0.01 },
  { min: 55837, max: 59186, rate: 0.02 },
  { min: 59187, max: 62738, rate: 0.025 },
  { min: 62739, max: 66502, rate: 0.03 },
  { min: 66503, max: 70492, rate: 0.035 },
  { min: 70493, max: 74722, rate: 0.04 },
  { min: 74723, max: 79206, rate: 0.045 },
  { min: 79207, max: 83958, rate: 0.05 },
  { min: 83959, max: 88996, rate: 0.055 },
  { min: 88997, max: 94336, rate: 0.06 },
  { min: 94337, max: 99996, rate: 0.065 },
  { min: 99997, max: 105996, rate: 0.07 },
  { min: 105997, max: 112356, rate: 0.075 },
  { min: 112357, max: 119097, rate: 0.08 },
  { min: 119098, max: 126243, rate: 0.085 },
  { min: 126244, max: 133818, rate: 0.09 },
  { min: 133819, max: 141847, rate: 0.095 },
  { min: 141848, max: Infinity, rate: 0.1 }
];

// Default values for the calculator
export const DEFAULT_VALUES = {
  grossIncome: 0,
  superRate: 11, // Keeping superannuation at 11% as that's the legal minimum
  taxDeductions: 0,
  hasHecsHelp: false,
  hecsDebtTotal: 0,
  additionalSuperContribution: 0
};

// Chart colors
export const CHART_COLORS = {
  takeHome: "hsl(142.1 76.2% 36.3%)", // success-500
  tax: "hsl(221.2 83.2% 53.3%)", // primary-500
  hecsHelp: "hsl(215.4 16.3% 46.9%)", // gray-500
  medicare: "hsl(262.1 83.3% 57.8%)", // secondary-500
  super: "hsl(24.6 95% 53.1%)", // orange-500
  taxBrackets: [
    "hsl(142.1 70.6% 45.3%)", // green-500
    "hsl(142.1 76.2% 36.3%)", // green-600
    "hsl(48 96.5% 53.1%)", // yellow-400
    "hsl(217.2 91.2% 59.8%)", // blue-500
    "hsl(0 72.2% 50.6%)", // red-500
  ]
};

// Form validation
export const VALIDATION_RULES = {
  grossIncome: {
    min: 0,
    max: 10000000
  },
  superRate: {
    min: 0,
    max: 100
  },
  taxDeductions: {
    min: 0,
    max: 1000000
  },
  hecsDebtTotal: {
    min: 0,
    max: 1000000
  },
  additionalSuperContribution: {
    min: 0,
    max: 1000000
  }
};

// PDF configuration
export const PDF_CONFIG = {
  title: "Income Analysis Report",
  disclaimer: "This report is generated for informational purposes only and should not be considered financial advice. Tax rates and calculations are based on Australian tax rules for the 2022-2023 financial year. Individual circumstances may vary, and we recommend consulting with a tax professional for personalized advice.",
  footer: "Generated by NumberLaunch — Crafted by Cloud Launch — delivering clarity with a lift."
};
