// Australian Tax Brackets for 2024-2025
// Base amounts calculated according to ATO formula for 2024-2025
export const TAX_BRACKETS = [
  { min: 0, max: 18200, rate: 0, base: 0 },
  { min: 18201, max: 45000, rate: 0.19, base: 0 },
  { min: 45001, max: 135000, rate: 0.30, base: 5092 },
  { min: 135001, max: 190000, rate: 0.37, base: 32092 },
  { min: 190001, max: Infinity, rate: 0.45, base: 52467 }
];

// Medicare Levy
export const MEDICARE_LEVY_RATE = 0.02;
export const MEDICARE_LEVY_THRESHOLD = 24276;
export const MEDICARE_LEVY_FAMILY_THRESHOLD = 40939;

// HECS/HELP Repayment Thresholds and Rates for 2024-2025
export const HECS_HELP_THRESHOLDS = [
  { min: 0, max: 51549, rate: 0 },
  { min: 51550, max: 59518, rate: 0.01 },
  { min: 59519, max: 63089, rate: 0.02 },
  { min: 63090, max: 66875, rate: 0.025 },
  { min: 66876, max: 70888, rate: 0.03 },
  { min: 70889, max: 75140, rate: 0.035 },
  { min: 75141, max: 79649, rate: 0.04 },
  { min: 79650, max: 84429, rate: 0.045 },
  { min: 84430, max: 89496, rate: 0.05 },
  { min: 89497, max: 94866, rate: 0.055 },
  { min: 94867, max: 100560, rate: 0.06 },
  { min: 100561, max: 106593, rate: 0.065 },
  { min: 106594, max: 113000, rate: 0.07 },
  { min: 113001, max: 119801, rate: 0.075 },
  { min: 119802, max: 127032, rate: 0.08 },
  { min: 127033, max: 134724, rate: 0.085 },
  { min: 134725, max: 142893, rate: 0.09 },
  { min: 142894, max: 151573, rate: 0.095 },
  { min: 151574, max: Infinity, rate: 0.1 }
];

// Default values for the calculator
export const DEFAULT_VALUES = {
  grossIncome: 0,
  superRate: 11, // Keeping superannuation at 11% as that's the legal minimum
  taxDeductions: 0,
  hasHecsHelp: false,
  hecsDebtTotal: 0,
  additionalSuperContribution: 0
};

// Chart colors
export const CHART_COLORS = {
  takeHome: "hsl(142.1 76.2% 36.3%)", // success-500
  tax: "hsl(221.2 83.2% 53.3%)", // primary-500
  hecsHelp: "hsl(215.4 16.3% 46.9%)", // gray-500
  medicare: "hsl(262.1 83.3% 57.8%)", // secondary-500
  super: "hsl(24.6 95% 53.1%)", // orange-500
  taxBrackets: [
    "hsl(142.1 70.6% 45.3%)", // green-500
    "hsl(142.1 76.2% 36.3%)", // green-600
    "hsl(48 96.5% 53.1%)", // yellow-400
    "hsl(217.2 91.2% 59.8%)", // blue-500
    "hsl(0 72.2% 50.6%)", // red-500
  ]
};

// Form validation
export const VALIDATION_RULES = {
  grossIncome: {
    min: 0,
    max: 10000000
  },
  superRate: {
    min: 0,
    max: 100
  },
  taxDeductions: {
    min: 0,
    max: 1000000
  },
  hecsDebtTotal: {
    min: 0,
    max: 1000000
  },
  additionalSuperContribution: {
    min: 0,
    max: 1000000
  }
};

// PDF configuration
export const PDF_CONFIG = {
  title: "Income Analysis Report",
  disclaimer: "This report is generated for informational purposes only and should not be considered financial advice. Tax rates and calculations are based on Australian tax rules for the 2024-2025 financial year, including the Stage 3 tax cuts. Individual circumstances may vary, and we recommend consulting with a tax professional for personalized advice.",
  footer: "Generated by NumberLaunch — Crafted by Cloud Launch — delivering clarity with a lift."
};
